language: python
python:
- '3.6'
- '3.7'
install:
- pip install -e .[dev]
script:
- pytest --cov=pylnd
- codecov --token=$CODECOV_TOKEN
deploy:
  provider: pypi
  user: gsmadi
  password:
    secure: 6YzC/Bhy8FnpqzfwzF6q127N3+/sjfFPiH82+gCJa52WG1d70/oMhtfy57ZpliijKW0phwWxHhCjAs0z1OUeIxe0wqYiLPrywFLwdnv2mj7bgWUir7lDfmLM6px6iylPq8Zx6qJkz6OJdHhV0An4TuOTFk6KOl+2hGw5XrdRfKtHvqYpTjRrR6/1Vbf57kyy+WanAsxfzneBFFMQDF8NbMGrv1zKtIfifkhCOX7LjbhCuIThdHe1QwXbCKG/z1w4/PC/mdL+p4LIYShVR815AgqHbOMBDbWHGEIU0dTNEeqq45eHKce3KOyOs/O/Bysj8d8gFA/KbpoM9sTx/mDNccjEXkWS6CCILeAN1Ti3J9kE8BsUgtQKDiDxPl0NA/asJ6CwkWoUMhl+akdkJO1JJpncw+Ab2+axIRQJf5DNg8dmXbzo1KB/PhZPENActwK/PqlAiMeBfl55Zi7XcsaU+4Uce1p79CYtAOuGU6e8U7VMcMv9AQRYhqgVfyaKFsbD3a35WrSm8jrUd/3IuXIOq6snXWGDSvKabz9gVbPMG9ZtrkrwBgLbSBj5eFdU5MmWhniRqRv6hyyKCEkD6gDh31nUT2MUpFOOLh19DYuM+O337rHjcMUJYv1Tw1UwULuzc+oS9j4/vYLepVdNu57J+RJIR23H3IqJm5g6qmMWzic=
  on:
    tags: true
  skip_existing: true
