language: python
python:
- '3.6'
- '3.7'
install:
- pip install -e .[dev]
script:
- pytest --cov=pylnd
- codecov --token=$CODECOV_TOKEN
deploy:
  provider: pypi
  user: gsmadi
  password:
    secure: FakEqJfdqJlGnOWo53yntG7RPu/7ojBVtA/CrE0e+fiSBSNVluM4ea9+H5zime0SGqggoSZrKhhgZ19EPE1EvEsXCN7vOTqwJ1kOCp8MMYY6KqxKTaFugU3BuJSjc73ZtF09SopCxGDW7DPMQ/RRuzjKHLe7I5SmrFqephAv477fTAU7OoDeHpl9sMW9GoR/6YUmJX9E4qzc03FDr1/+6pWDTUGP9IE6VIL8wzfcFL4f8N/CZTk9mKyPKqWKSYwAbvchzUecVc/L7UutNXBJCbuaGG38ykmZ5Mrr6PPzprv8OGuSkCZJdGWPoWUZWv0KUAncoVJjAvsPmtismB7jO36Ca1C66Lkw0PKhbCEpJK/wc/kR5wybAV+GaL8MD1Ex6wfpslNH3cCm9hbjehWeNOeFrcjuSJsrwdRP+gUV3mxA7HlNn2FcfugqoVkj0a3l8Y0dgabUvuWtMjQxKKQtKkh7kj9X+T4XrmhCUvyFKKxBqHcZg/Tk1q4G56Jb/WtK95PVO3DVdhvVuNM5PdnkLfYdCbQo5OhQprvI+eRcVZHtZ/cAvKHAxRVsuODTRfztGkHr5f0kYMI2S4H/UTbXN3xQbXidR5ph7X2jQK9OKpWj8pQWmnGheQgtgDd5xjVQGNROHo9p2cIcYppcESch+ptl80UvrsFfoswxkx66JcI=
  on:
    tags: true
  skip_existing: true
